name: image_cropper_mobile
description: Revolutionary AI-Powered Image Cropper - Advanced Mobile Image Processing
version: 2.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI
  cupertino_icons: ^1.0.0
  google_fonts: ^6.0.0
  
  # State Management
  flutter_bloc: ^8.1.0
  bloc: ^8.1.0
  equatable: ^2.0.0
  
  # Image Processing
  image_picker: ^1.0.0
  image: ^4.0.0
  
  # File Handling
  path_provider: ^2.0.0
  permission_handler: ^11.0.0
  
  # Animations
  flutter_animate: ^4.0.0
  
  # Network & API
  dio: ^5.0.0
  
  # Storage
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
