name: image_cropper_mobile
description: Professional Image Cropping Tool for Android - Crop images into beautiful shapes
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  material_symbols_icons: ^4.2719.3
  
  # Image Processing
  image_picker: ^1.1.2
  image: ^4.3.0
  flutter_image_compress: ^2.4.0
  image_cropper: ^8.0.1
  
  # File Handling
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  
  # State Management
  provider: ^6.1.1
  
  # UI Enhancements
  # flutter_spinkit: ^5.2.1
  # lottie: ^2.7.0
  # shimmer: ^3.0.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Platform Integration
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/kowalski.png"
  min_sdk_android: 21
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
